name: Documentation

on:
  push:
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.1
      - run: pnpm i
      - run: pnpm run docs
      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: docs
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
